export const RESUME_FILE_TYPE_CODE = "RESUME";
export const COVER_LETTER_FILE_TYPE_CODE = "COVER_LETTER";
export const PORTFOLIO_FILE_TYPE_CODE = "PORTFOLIO";
export const REFERENCE_CHECK_FILE_TYPE_CODE = "REFERENCE_CHECK";
export const FEE_AGREEMENT_FILE_TYPE_CODE = "FEE_AGREEMENT";
