export const API_MAX_FILE_SIZE_IN_BYTE = 20971520; // 20MB
export const E_VALIDATION_FAILED = "E_VALIDATION_FAILED";
export const E_UNEXPECTED_ERROR = "E_UNEXPECTED_ERROR";

export const DRAFT_POST_TYPE = "DRAFT";
export const PUBLISHED_POST_TYPE = "PUBLISHED";
