export const ROLE_DIRECTOR_CODE = "DIRECTOR";
export const ROLE_DIRECTOR_API_PREFIX = "directors";
export const ROLE_COACH_CODE = "COACH";
export const ROLE_COACH_API_PREFIX = "coaches";
export const ROLE_RECRUITER_CODE = "RECRUITER";
export const ROLE_RECRUITER_API_PREFIX = "recruiters";

export const TALENT_COMPONENT_ = "TALENT_COMPONENT_";
export const TALENT_COMPONENT_DISCARD = "TALENT_COMPONENT_DISCARD";
export const COMPANY_COMPONENT_ADD_COMPANY = "COMPANY_COMPONENT_ADD_COMPANY";
export const COMPANY_COMPONENT_SAVE = "COMPANY_COMPONENT_SAVE";
export const MARKET_COMPONENT_ADD_NEW_TALENT =
  "MARKET_COMPONENT_ADD_NEW_TALENT";
export const TALENT_COMPONENT_SAVE_AS_DRAFT = "TALENT_COMPONENT_SAVE_AS_DRAFT";
export const TALENT_COMPONENT_SAVE_AND_SEND_TO_COACH =
  "TALENT_COMPONENT_SAVE_AND_SEND_TO_COACH";
export const TALENT_COMPONENT_ATTACHMENTS_DESTROY =
  "TALENT_COMPONENT_ATTACHMENTS_DESTROY";
export const TALENT_COMPONENT_ATTACHMENTS_SUBMIT =
  "TALENT_COMPONENT_ATTACHMENTS_SUBMIT";

export const DIRECTOR_COMPONENT_PERMISSIONS = [
  COMPANY_COMPONENT_ADD_COMPANY,
  COMPANY_COMPONENT_SAVE,
];

export const COACH_COMPONENT_PERMISSIONS = [TALENT_COMPONENT_DISCARD];

export const RECRUITER_COMPONENT_PERMISSIONS = [
  MARKET_COMPONENT_ADD_NEW_TALENT,
  TALENT_COMPONENT_SAVE_AS_DRAFT,
  TALENT_COMPONENT_SAVE_AND_SEND_TO_COACH,
  TALENT_COMPONENT_DISCARD,
  TALENT_COMPONENT_ATTACHMENTS_DESTROY,
  TALENT_COMPONENT_ATTACHMENTS_SUBMIT,
];
