export const COMPANY_CLEAR = "COMPANY_CLEAR";
export const COMPANY_INIT = "COMPANY_INIT";
export const COMPANY_GET = "COMPANY_GET";
export const COMPANY_GET_SUCCESS = "COMPANY_GET_SUCCESS";
export const COMPANY_GET_FAILURE = "COMPANY_GET_FAILURE";

export const COMPANY_GET_ALL = "COMPANY_GET_ALL";
export const COMPANY_GET_ALL_CLEAR = "COMPANY_GET_ALL_CLEAR";
export const COMPANY_GET_ALL_SUCCESS = "COMPANY_GET_ALL_SUCCESS";
export const COMPANY_GET_ALL_FAILURE = "COMPANY_GET_ALL_FAILURE";
export const COMPANY_STORE = "COMPANY_STORE";
export const COMPANY_STORE_SUCCESS = "COMPANY_STORE_SUCCESS";
export const COMPANY_STORE_FAILURE = "COMPANY_STORE_FAILURE";
export const COMPANY_PATCH = "COMPANY_PATCH";
export const COMPANY_PATCH_SUCCESS = "COMPANY_PATCH_SUCCESS";
export const COMPANY_PATCH_FAILURE = "COMPANY_PATCH_FAILURE";

export const COMPANY_TYPE_GET_ALL = "COMPANY_TYPE_GET_ALL";
export const COMPANY_TYPE_GET_ALL_SUCCESS = "COMPANY_TYPE_GET_ALL_SUCCESS";
export const COMPANY_TYPE_GET_ALL_FAILURE = "COMPANY_TYPE_GET_ALL_FAILURE";
