export const LOCATION_GET_ALL = "LOCATION_GET_ALL";
export const LOCATION_GET_ALL_CLEAR = "LOCATION_GET_ALL_CLEAR";
export const LOCATION_GET_ALL_SUCCESS = "LOCATION_GET_ALL_SUCCESS";
export const LOCATION_GET_ALL_FAILURE = "LOCATION_GET_ALL_FAILURE";

export const INDUSTRY_GET_ALL = "INDUSTRY_GET_ALL";
export const INDUSTRY_GET_ALL_SUCCESS = "INDUSTRY_GET_ALL_SUCCESS";
export const INDUSTRY_GET_ALL_FAILURE = "INDUSTRY_GET_ALL_FAILURE";

export const STATUS_GET_ALL = "STATUS_GET_ALL";
export const STATUS_GET_ALL_SUCCESS = "STATUS_GET_ALL_SUCCESS";
export const STATUS_GET_ALL_FAILURE = "STATUS_GET_ALL_FAILURE";

export const FUNCTIONAL_TITLE_GET_ALL = "FUNCTIONAL_TITLE_GET_ALL";
export const FUNCTIONAL_TITLE_GET_ALL_SUCCESS =
  "FUNCTIONAL_TITLE_GET_ALL_SUCCESS";

export const FUNCTIONAL_TITLE_GET_ALL_FAILURE =
  "FUNCTIONAL_TITLE_GET_ALL_FAILURE";

export const SENIORITY_GET_ALL = "SENIORITY_GET_ALL";
export const SENIORITY_GET_ALL_SUCCESS = "SENIORITY_GET_ALL_SUCCESS";
export const SENIORITY_GET_ALL_FAILURE = "SENIORITY_GET_ALL_FAILURE";

export const PROCESS_STATUS_GET_ALL = "PROCESS_STATUS_GET_ALL";
export const PROCESS_STATUS_GET_ALL_SUCCESS = "PROCESS_STATUS_GET_ALL_SUCCESS";
export const PROCESS_STATUS_GET_ALL_FAILURE = "PROCESS_STATUS_GET_ALL_FAILURE";

export const RELOCATION_GET_ALL = "RELOCATION_GET_ALL";
export const RELOCATION_GET_ALL_SUCCESS = "RELOCATION_GET_ALL_SUCCESS";
export const RELOCATION_GET_ALL_FAILURE = "RELOCATION_GET_ALL_FAILURE";

export const CURRENCY_GET_ALL = "CURRENCY_GET_ALL";
export const CURRENCY_GET_ALL_SUCCESS = "CURRENCY_GET_ALL_SUCCESS";
export const CURRENCY_GET_ALL_FAILURE = "CURRENCY_GET_ALL_FAILURE";
