export const TALENT_CLEAR = "TALENT_CLEAR";
export const TALENT_INIT = "TALENT_INIT";
export const TALENT_GET = "TALENT_GET";
export const TALENT_GET_SUCCESS = "TALENT_GET_SUCCESS";
export const TALENT_GET_FAILURE = "TALENT_GET_FAILURE";

export const TALENT_GET_ALL = "TALENT_GET_ALL";
export const TALENT_GET_ALL_CLEAR = "TALENT_GET_ALL_CLEAR";
export const TALENT_GET_ALL_SUCCESS = "TALENT_GET_ALL_SUCCESS";
export const TALENT_GET_ALL_FAILURE = "TALENT_GET_ALL_FAILURE";

export const TALENT_STORE = "TALENT_STORE";
export const TALENT_STORE_SUCCESS = "TALENT_STORE_SUCCESS";
export const TALENT_STORE_FAILURE = "TALENT_STORE_FAILURE";
export const TALENT_PATCH = "TALENT_PATCH";
export const TALENT_PATCH_SUCCESS = "TALENT_PATCH_SUCCESS";
export const TALENT_PATCH_FAILURE = "TALENT_PATCH_FAILURE";
export const TALENT_DESTROY = "TALENT_DESTROY";
export const TALENT_DESTROY_SUCCESS = "TALENT_DESTROY_SUCCESS";
export const TALENT_DESTROY_FAILURE = "TALENT_DESTROY_FAILURE";

export const TALENT_FILE_GET_ALL = "TALENT_FILE_GET_ALL";
export const TALENT_FILE_GET_ALL_CLEAR = "TALENT_FILE_GET_ALL_CLEAR";
export const TALENT_FILE_GET_ALL_SUCCESS = "TALENT_FILE_GET_ALL_SUCCESS";
export const TALENT_FILE_GET_ALL_FAILURE = "TALENT_FILE_GET_ALL_FAILURE";

export const TALENT_FILE_UPLOAD = "TALENT_FILE_UPLOAD";
export const TALENT_FILE_UPLOAD_INIT = "TALENT_FILE_UPLOAD_INIT";
export const TALENT_FILE_UPLOAD_CLEAR = "TALENT_FILE_UPLOAD_CLEAR";
export const TALENT_FILE_UPLOAD_SUCCESS = "TALENT_FILE_UPLOAD_SUCCESS";
export const TALENT_FILE_UPLOAD_FAILURE = "TALENT_FILE_UPLOAD_FAILURE";

export const TALENT_FILE_DESTROY = "TALENT_FILE_DESTROY";
export const TALENT_FILE_DESTROY_SUCCESS = "TALENT_FILE_DESTROY_SUCCESS";
export const TALENT_FILE_DESTROY_FAILURE = "TALENT_FILE_DESTROY_FAILURE";

export const TALENT_FILE_STATE_ID_REMOVE = "TALENT_FILE_STATE_ID_REMOVE";
